### ISSUE TITLE
Restart scraper on morph.io

### ISSUE THREAD

**Issue by dcalde** [stanle/cityperthscraper#2]
Hi,

Thanks for merging my PR. I was hoping that morph.io might detect that there has been a change and automatically restart the scraper, but it didn't. Could you please do so manually?
https://morph.io/stanle/cityperthscraper

Thanks,
Daniel

**Comment by stanle** [comment]
Hi Daniel.

the run failed with the error below.

```
Injecting scraper and running...
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/app/.heroku/python/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/app/.heroku/python/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scraper.py", line 43, in <module>
    with Browser('chrome', options=chrome_options) as browser:
  File "/app/.heroku/python/lib/python3.6/site-packages/splinter/browser.py", line 92, in Browser
    return get_driver(driver, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/splinter/browser.py", line 70, in get_driver
    raise err
  File "/app/.heroku/python/lib/python3.6/site-packages/splinter/browser.py", line 66, in get_driver
    return driver(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/splinter/driver/webdriver/chrome.py", line 43, in __init__
    self.driver = Chrome(options=options, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

```

**Comment by stanle** [comment]
Run successfully. Good job.

**Comment by stanle** [comment]
A second run was also successful and only scraped and successfully ignored known files. 
I set it to auto-run.
